-- AlterTable
ALTER TABLE `Major` ADD COLUMN `dayaTampung` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `majorType` ENUM('SAINTEK', 'SOSHUM') NOT NULL DEFAULT 'SAINTEK',
    ADD COLUMN `peminat` INTEGER NOT NULL DEFAULT 0;
